const pool = require('../db');

exports.getAllPurchaseOrders = async (req, res) => {
    let conn;
    try {
        conn = await pool.getConnection();
        const rows = await conn.query(`
      SELECT po.*, s.name as supplier_name, u.name as created_by_name 
      FROM PURCHASE_ORDERS po
      JOIN SUPPLIERS s ON po.supplier_id = s.id
      LEFT JOIN USERS u ON po.created_by = u.id
      ORDER BY po.created_at DESC
    `);
        res.json(rows.map(r => ({
            ...r,
            id: r.id.toString(),
            supplier_id: r.supplier_id.toString(),
            total_amount: Number(r.total_amount)
        })));
    } catch (err) {
        console.error(err);
        res.status(500).json({ message: 'Server error retrieving POs' });
    } finally {
        if (conn) conn.release();
    }
};

exports.createPurchaseOrder = async (req, res) => {
    const { supplier_id, total_amount, items, status } = req.body;
    if (!supplier_id) {
        return res.status(400).json({ message: 'Missing required field: supplier_id' });
    }

    let conn;
    try {
        conn = await pool.getConnection();
        await conn.beginTransaction();

        const poStatus = status || 'PENDING';

        const poResult = await conn.query(
            'INSERT INTO PURCHASE_ORDERS (supplier_id, status, total_amount, created_by) VALUES (?, ?, ?, ?)',
            [supplier_id, poStatus, total_amount || 0, req.user.id]
        );

        const poId = poResult.insertId;

        if (items && items.length > 0) {
            for (let item of items) {
                await conn.query(
                    'INSERT INTO PURCHASE_ORDER_ITEMS (purchase_order_id, product_id, ordered_quantity, cost_price) VALUES (?, ?, ?, ?)',
                    [poId, item.product_id, item.ordered_quantity, item.cost_price]
                );
            }
        }

        await conn.commit();
        res.status(201).json({ message: 'Purchase Order created', id: poId.toString() });
    } catch (err) {
        console.error(err);
        if (conn) await conn.rollback();
        res.status(500).json({ message: 'Server error' });
    } finally {
        if (conn) conn.release();
    }
};

exports.updatePurchaseOrder = async (req, res) => {
    const poId = req.params.id;
    const { total_amount, status } = req.body;

    let conn;
    try {
        conn = await pool.getConnection();

        let updateFields = [];
        let params = [];

        if (total_amount !== undefined) {
            updateFields.push('total_amount = ?');
            params.push(total_amount);
        }

        if (status !== undefined) {
            updateFields.push('status = ?');
            params.push(status);
        }

        if (updateFields.length === 0) {
            return res.status(400).json({ message: 'No fields to update' });
        }

        params.push(poId);

        const result = await conn.query(
            `UPDATE PURCHASE_ORDERS SET ${updateFields.join(', ')} WHERE id = ?`,
            params
        );

        if (result.affectedRows === 0) {
            return res.status(404).json({ message: 'Purchase order not found' });
        }

        res.json({ message: 'Purchase order updated successfully' });
    } catch (err) {
        console.error(err);
        res.status(500).json({ message: 'Server error updating PO' });
    } finally {
        if (conn) conn.release();
    }
};

exports.autoGeneratePO = async (req, res) => {
    const { product_id, recommended_qty, expected_demand, confidence } = req.body;

    if (!product_id || recommended_qty === undefined) {
        return res.status(400).json({ message: 'Missing product or quantity for auto-generation' });
    }

    let conn;
    try {
        conn = await pool.getConnection();

        // 1. Get product details (supplier, cost)
        const productRows = await conn.query('SELECT supplier_id, cost_price FROM PRODUCTS WHERE id = ?', [product_id]);

        if (productRows.length === 0) {
            return res.status(404).json({ message: 'Product not found' });
        }

        const product = productRows[0];
        if (!product.supplier_id) {
            return res.status(400).json({ message: 'Product has no assigned supplier. Cannot auto-generate PO.' });
        }

        const total_amount = Number(product.cost_price) * Number(recommended_qty);

        await conn.beginTransaction();

        // 2. Create the drafted PO
        const notes = `Auto-generated by Smart Inventory Assistant.\nExpected 14-day demand: ${expected_demand || 'Unknown'}\nML Confidence: ${confidence || 'Unknown'}`;

        // We might not have a notes field in the schema, so we just use the status. 
        // Real systems would have a notes/remarks column.
        const poResult = await conn.query(
            'INSERT INTO PURCHASE_ORDERS (supplier_id, status, total_amount, created_by) VALUES (?, ?, ?, ?)',
            [product.supplier_id, 'PENDING', total_amount, req.user.id] // req.user.id from authMiddleware
        );

        const poId = poResult.insertId;

        // 3. Add the line item
        await conn.query(
            'INSERT INTO PURCHASE_ORDER_ITEMS (purchase_order_id, product_id, ordered_quantity, cost_price) VALUES (?, ?, ?, ?)',
            [poId, product_id, recommended_qty, product.cost_price]
        );

        await conn.commit();
        res.status(201).json({
            message: 'Purchase Order auto-generated successfully',
            po_id: poId.toString()
        });

    } catch (err) {
        console.error('Error auto-generating PO:', err);
        if (conn) await conn.rollback();
        res.status(500).json({ message: 'Server error generating PO' });
    } finally {
        if (conn) conn.release();
    }
};

exports.deletePurchaseOrder = async (req, res) => {
    const poId = req.params.id;
    let conn;
    try {
        conn = await pool.getConnection();

        // 1. Check status
        const [po] = await conn.query('SELECT status FROM PURCHASE_ORDERS WHERE id = ?', [poId]);
        if (!po) {
            return res.status(404).json({ message: 'Purchase order not found' });
        }

        if (po.status === 'RECEIVED' || po.status === 'APPROVED') {
            return res.status(400).json({ message: 'Cannot delete an approved or received purchase order to prevent inventory corruption.' });
        }

        await conn.beginTransaction();

        // 2. Delete line items first (if no cascade)
        await conn.query('DELETE FROM PURCHASE_ORDER_ITEMS WHERE purchase_order_id = ?', [poId]);

        // 3. Delete PO itself
        await conn.query('DELETE FROM PURCHASE_ORDERS WHERE id = ?', [poId]);

        await conn.commit();
        res.json({ message: 'Purchase order deleted successfully' });
    } catch (err) {
        console.error('Error deleting PO:', err);
        if (conn) await conn.rollback();
        res.status(500).json({ message: 'Server error deleting PO' });
    } finally {
        if (conn) conn.release();
    }
};
