CREATE TABLE IF NOT EXISTS USERS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('owner','manager','staff','warehouse') NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS LOCATIONS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  address TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS SUPPLIERS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  phone VARCHAR(50),
  address TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CATEGORIES (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT
);

CREATE TABLE IF NOT EXISTS PRODUCTS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  sku VARCHAR(100) UNIQUE NOT NULL,
  category_id INT,
  supplier_id INT,
  cost_price DECIMAL(10,2) NOT NULL,
  selling_price DECIMAL(10,2) NOT NULL,
  reorder_level INT DEFAULT 0,
  track_expiry BOOLEAN DEFAULT FALSE,
  track_batch BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (category_id) REFERENCES CATEGORIES(id) ON DELETE SET NULL,
  FOREIGN KEY (supplier_id) REFERENCES SUPPLIERS(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS PRODUCT_BATCHES (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product_id INT NOT NULL,
  batch_number VARCHAR(100),
  expiry_date DATE,
  quantity INT DEFAULT 0,
  location_id INT NOT NULL,
  FOREIGN KEY (product_id) REFERENCES PRODUCTS(id) ON DELETE CASCADE,
  FOREIGN KEY (location_id) REFERENCES LOCATIONS(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS INVENTORY (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product_id INT NOT NULL,
  location_id INT NOT NULL,
  quantity INT DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (product_id) REFERENCES PRODUCTS(id) ON DELETE CASCADE,
  FOREIGN KEY (location_id) REFERENCES LOCATIONS(id) ON DELETE CASCADE,
  UNIQUE KEY idx_product_location (product_id, location_id)
);

CREATE TABLE IF NOT EXISTS STOCK_MOVEMENTS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product_id INT NOT NULL,
  location_id INT NOT NULL,
  type ENUM('IN','OUT','TRANSFER','ADJUSTMENT') NOT NULL,
  quantity INT NOT NULL,
  reference_type VARCHAR(50), 
  reference_id INT,
  performed_by INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (product_id) REFERENCES PRODUCTS(id) ON DELETE CASCADE,
  FOREIGN KEY (location_id) REFERENCES LOCATIONS(id) ON DELETE CASCADE,
  FOREIGN KEY (performed_by) REFERENCES USERS(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS PURCHASE_ORDERS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  supplier_id INT NOT NULL,
  po_number VARCHAR(100),
  po_date DATE,
  valid_from DATE,
  valid_to DATE,
  shipping_address TEXT,
  status ENUM('DRAFT','PENDING','APPROVED','RECEIVED') DEFAULT 'DRAFT',
  total_amount DECIMAL(10,2) DEFAULT 0,
  created_by INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (supplier_id) REFERENCES SUPPLIERS(id) ON DELETE RESTRICT,
  FOREIGN KEY (created_by) REFERENCES USERS(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS PURCHASE_ORDER_ITEMS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  purchase_order_id INT NOT NULL,
  product_id INT NOT NULL,
  ordered_quantity INT NOT NULL,
  received_quantity INT DEFAULT 0,
  cost_price DECIMAL(10,2) NOT NULL,
  tax_percentage DECIMAL(5,2) DEFAULT 0,
  FOREIGN KEY (purchase_order_id) REFERENCES PURCHASE_ORDERS(id) ON DELETE CASCADE,
  FOREIGN KEY (product_id) REFERENCES PRODUCTS(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS SALES_HISTORY (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product_id INT NOT NULL,
  location_id INT NOT NULL,
  quantity_sold INT NOT NULL,
  sale_date DATE NOT NULL,
  FOREIGN KEY (product_id) REFERENCES PRODUCTS(id) ON DELETE CASCADE,
  FOREIGN KEY (location_id) REFERENCES LOCATIONS(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS AUDIT_LOGS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT,
  action VARCHAR(255) NOT NULL,
  entity_type VARCHAR(100) NOT NULL,
  entity_id INT NOT NULL,
  old_value JSON,
  new_value JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE SET NULL
);
